export const data = {
    header: [
        { title: "Home", link: "/home" },
        { title: "Bollywood", link: "/category/bollywood" },
        { title: "Technology", link: "/category/technology" },
        { title: "Hollywood", link: "/category/hollywood" },
        { title: "Fitness", link: "/category/fitness" },
        { title: "Food", link: "/category/food" }
      ],
      MainBlogArr: [
        { id: 1, title: "Title of verticle gallery", type: "Travel", date: "August 21 2017", imgpath: "../photo-1.jfif" },
        { id: 2, title: "The Sound cloud You loved is doomed", type: "Travel", date: "August 21 2017", imgpath: "../photo-2.jpg" },
        { id: 3, title: "The Sound cloud You loved is doomed", type: "Travel", date: "August 21 2017", imgpath: "../photo-2.jpg" }
      ],
      LatestBlogArr: [
        {
          id: 1,
          title: "Joshua Tree Overnight Adventure",
          type: "Travel",
          date: "August 21 2017",
          imgpath: "../../photo-1.jfif",
          author:"Dmitry Nozhenko",
          description: "Gujarat is vastly underrated and it's a mystery to us why the region isn't more well known as a tourist destination. It has a plethora of temples and palaces."
        },
        {
          id: 2,
          title: "Joshua Tree Overnight Adventure",
          type: "Travel",
          date: "August 21 2017",
          imgpath: "../../photo-1.jfif",
          author:"Dmitry Nozhenko",
          description: "Gujarat is vastly underrated and it's a mystery to us why the region isn't more well known as a tourist destination. It has a plethora of temples and palaces."
        },
        {
          id: 3,
          title: "Joshua Tree Overnight Adventure",
          type: "Travel",
          date: "August 21 2017",
          imgpath: "../../photo-1.jfif",
          author:"Dmitry Nozhenko",
          description: "Gujarat is vastly underrated and it's a mystery to us why the region isn't more well known as a tourist destination. It has a plethora of temples and palaces."
        }
      ],
      LatestArticleArr: [
        {
          id: 1,
          title: "Catch waves with an adventure guide",
          type: "Travel",
          date: "August 21 2017",
          imgpath: "../photo-1.jfif",
          description: "Gujarat is vastly underrated and it's a mystery to us why the region isn't more well known as a tourist destination.",
        },
        {
          id: 2,
          title: "Catch waves with an adventure guide",
          type: "Travel",
          date: "August 21 2017",
          imgpath: "../photo-1.jfif",
          description: "Gujarat is vastly underrated and it's a mystery to us why the region isn't more well known as a tourist destination.",
        },
        {
          id: 3,
          title: "Catch waves with an adventure guide",
          type: "Travel",
          date: "August 21 2017",
          imgpath: "../photo-1.jfif",
          description: "Gujarat is vastly underrated and it's a mystery to us why the region isn't more well known as a tourist destination.",
        },
        {
          id: 4,
          title: "Catch waves with an adventure guide",
          type: "Travel",
          date: "August 21 2017",
          imgpath: "../photo-1.jfif",
          description: "Gujarat is vastly underrated and it's a mystery to us why the region isn't more well known as a tourist destination.",
        }
      ],
      TopPosts:[
        {
          id: 1,
          title: "Catch waves with an adventure guide",
          type: "Travel",
          date: "August 21 2017",
          imgpath: "../photo-1.jfif",
          description: "Gujarat is vastly underrated and it's a mystery to us why the region isn't more well known as a tourist destination.",
        },
        {
          id: 2,
          title: "Catch waves with an adventure guide",
          type: "Travel",
          date: "August 21 2017",
          imgpath: "../photo-1.jfif",
          description: "Gujarat is vastly underrated and it's a mystery to us why the region isn't more well known as a tourist destination.",
        },
        {
          id: 3,
          title: "Catch waves with an adventure guide",
          type: "Travel",
          date: "August 21 2017",
          imgpath: "../photo-1.jfif",
          description: "Gujarat is vastly underrated and it's a mystery to us why the region isn't more well known as a tourist destination.",
        },
        {
          id: 4,
          title: "Catch waves with an adventure guide",
          type: "Travel",
          date: "August 21 2017",
          imgpath: "../photo-1.jfif",
          description: "Gujarat is vastly underrated and it's a mystery to us why the region isn't more well known as a tourist destination.",
        }
      ],
      LatestStoriesArr:[
        {
          id: 1,
          title: "Catch waves with an adventure guide",
          type: "Tech",
          date: "Today At 11:54",
          imgpath: "../photo-1.jfif",
          description: "Gujarat is vastly underrated and it's a mystery to us why the region isn't more well known as a tourist destination. It has a plethora of temples and palaces. Gujarat is vastly underrated and it's a mystery to us why the region isn't more well-known as a tourist destination. It has a plethore of temples and palaces.",
        },
        {
          id: 2,
          title: "Catch waves with an adventure guide",
          type: "Style",
          date: "August 21 2017",
          imgpath: "../photo-1.jfif",
          description: "Gujarat is vastly underrated and it's a mystery to us why the region isn't more well known as a tourist destination. It has a plethora of temples and palaces. Gujarat is vastly underrated and it's a mystery to us why the region isn't more well-known as a tourist destination. It has a plethore of temples and palaces.",
        },
        {
          id: 1,
          title: "Catch waves with an adventure guide",
          type: "Tech",
          date: "August 21 2017",
          imgpath: "../photo-1.jfif",
          description: "Gujarat is vastly underrated and it's a mystery to us why the region isn't more well known as a tourist destination. It has a plethora of temples and palaces. Gujarat is vastly underrated and it's a mystery to us why the region isn't more well-known as a tourist destination. It has a plethore of temples and palaces.",
        },
      ],
      bollywood: {
        'title': 'Bollywood',
        'TopPosts': [
            {
                id: 1,
                title: "Catch waves with an adventure guide",
                type: "Travel",
                date: "August 21 2017",
                imgpath: "../photo-1.jfif",
                description: "Gujarat is vastly underrated and it's a mystery to us why the region isn't more well known as a tourist destination.",
            },
            {
                id: 2,
                title: "Catch waves with an adventure guide",
                type: "Travel",
                date: "August 21 2017",
                imgpath: "../photo-1.jfif",
                description: "Gujarat is vastly underrated and it's a mystery to us why the region isn't more well known as a tourist destination.",
            },
            {
                id: 3,
                title: "Catch waves with an adventure guide",
                type: "Travel",
                date: "August 21 2017",
                imgpath: "../photo-1.jfif",
                description: "Gujarat is vastly underrated and it's a mystery to us why the region isn't more well known as a tourist destination.",
            },
            {
                id: 4,
                title: "Catch waves with an adventure guide",
                type: "Travel",
                date: "August 21 2017",
                imgpath: "../photo-1.jfif",
                description: "Gujarat is vastly underrated and it's a mystery to us why the region isn't more well known as a tourist destination.",
            }
        ],
        'LatestArticleArr': [
            {
                id: 1,
                title: "Catch waves with an adventure guide",
                type: "Travel",
                date: "August 21 2017",
                imgpath: "../photo-1.jfif",
                description: "Gujarat is vastly underrated and it's a mystery to us why the region isn't more well known as a tourist destination.",
            },
            {
                id: 2,
                title: "Catch waves with an adventure guide",
                type: "Travel",
                date: "August 21 2017",
                imgpath: "../photo-1.jfif",
                description: "Gujarat is vastly underrated and it's a mystery to us why the region isn't more well known as a tourist destination.",
            },
            {
                id: 3,
                title: "Catch waves with an adventure guide",
                type: "Travel",
                date: "August 21 2017",
                imgpath: "../photo-1.jfif",
                description: "Gujarat is vastly underrated and it's a mystery to us why the region isn't more well known as a tourist destination.",
            },
            {
                id: 4,
                title: "Catch waves with an adventure guide",
                type: "Travel",
                date: "August 21 2017",
                imgpath: "../photo-1.jfif",
                description: "Gujarat is vastly underrated and it's a mystery to us why the region isn't more well known as a tourist destination.",
            },
            {
                id: 5,
                title: "Catch waves with an adventure guide",
                type: "Travel",
                date: "August 21 2017",
                imgpath: "../photo-1.jfif",
                description: "Gujarat is vastly underrated and it's a mystery to us why the region isn't more well known as a tourist destination.",
            },
            {
                id: 6,
                title: "Catch waves with an adventure guide",
                type: "Travel",
                date: "August 21 2017",
                imgpath: "../photo-1.jfif",
                description: "Gujarat is vastly underrated and it's a mystery to us why the region isn't more well known as a tourist destination.",
            },
            {
                id: 7,
                title: "Catch waves with an adventure guide",
                type: "Travel",
                date: "August 21 2017",
                imgpath: "../photo-1.jfif",
                description: "Gujarat is vastly underrated and it's a mystery to us why the region isn't more well known as a tourist destination.",
            }
        ]
    },
    technology: {
        'title': 'Technology',
        'TopPosts': [
            {
                id: 1,
                title: "Catch waves with an adventure guide",
                type: "Travel",
                date: "August 21 2017",
                imgpath: "../photo-1.jfif",
                description: "Gujarat is vastly underrated and it's a mystery to us why the region isn't more well known as a tourist destination.",
            },
            {
                id: 2,
                title: "Catch waves with an adventure guide",
                type: "Travel",
                date: "August 21 2017",
                imgpath: "../photo-1.jfif",
                description: "Gujarat is vastly underrated and it's a mystery to us why the region isn't more well known as a tourist destination.",
            },
            {
                id: 3,
                title: "Catch waves with an adventure guide",
                type: "Travel",
                date: "August 21 2017",
                imgpath: "../photo-1.jfif",
                description: "Gujarat is vastly underrated and it's a mystery to us why the region isn't more well known as a tourist destination.",
            },
            {
                id: 4,
                title: "Catch waves with an adventure guide",
                type: "Travel",
                date: "August 21 2017",
                imgpath: "../photo-1.jfif",
                description: "Gujarat is vastly underrated and it's a mystery to us why the region isn't more well known as a tourist destination.",
            }
        ],
        'LatestArticleArr': [
            {
                id: 1,
                title: "Catch waves with an adventure guide",
                type: "Travel",
                date: "August 21 2017",
                imgpath: "../photo-1.jfif",
                description: "Gujarat is vastly underrated and it's a mystery to us why the region isn't more well known as a tourist destination.",
            },
            {
                id: 2,
                title: "Catch waves with an adventure guide",
                type: "Travel",
                date: "August 21 2017",
                imgpath: "../photo-1.jfif",
                description: "Gujarat is vastly underrated and it's a mystery to us why the region isn't more well known as a tourist destination.",
            },
            {
                id: 3,
                title: "Catch waves with an adventure guide",
                type: "Travel",
                date: "August 21 2017",
                imgpath: "../photo-1.jfif",
                description: "Gujarat is vastly underrated and it's a mystery to us why the region isn't more well known as a tourist destination.",
            },
            {
                id: 4,
                title: "Catch waves with an adventure guide",
                type: "Travel",
                date: "August 21 2017",
                imgpath: "../photo-1.jfif",
                description: "Gujarat is vastly underrated and it's a mystery to us why the region isn't more well known as a tourist destination.",
            },
            {
                id: 5,
                title: "Catch waves with an adventure guide",
                type: "Travel",
                date: "August 21 2017",
                imgpath: "../photo-1.jfif",
                description: "Gujarat is vastly underrated and it's a mystery to us why the region isn't more well known as a tourist destination.",
            },
            {
                id: 6,
                title: "Catch waves with an adventure guide",
                type: "Travel",
                date: "August 21 2017",
                imgpath: "../photo-1.jfif",
                description: "Gujarat is vastly underrated and it's a mystery to us why the region isn't more well known as a tourist destination.",
            },
            {
                id: 7,
                title: "Catch waves with an adventure guide",
                type: "Travel",
                date: "August 21 2017",
                imgpath: "../photo-1.jfif",
                description: "Gujarat is vastly underrated and it's a mystery to us why the region isn't more well known as a tourist destination.",
            }
        ]
    },
    hollywood: {
        'title': 'Hollywood',
        'TopPosts': [
            {
                id: 1,
                title: "Catch waves with an adventure guide",
                type: "Travel",
                date: "August 21 2017",
                imgpath: "../photo-1.jfif",
                description: "Gujarat is vastly underrated and it's a mystery to us why the region isn't more well known as a tourist destination.",
            },
            {
                id: 2,
                title: "Catch waves with an adventure guide",
                type: "Travel",
                date: "August 21 2017",
                imgpath: "../photo-1.jfif",
                description: "Gujarat is vastly underrated and it's a mystery to us why the region isn't more well known as a tourist destination.",
            },
            {
                id: 3,
                title: "Catch waves with an adventure guide",
                type: "Travel",
                date: "August 21 2017",
                imgpath: "../photo-1.jfif",
                description: "Gujarat is vastly underrated and it's a mystery to us why the region isn't more well known as a tourist destination.",
            },
            {
                id: 4,
                title: "Catch waves with an adventure guide",
                type: "Travel",
                date: "August 21 2017",
                imgpath: "../photo-1.jfif",
                description: "Gujarat is vastly underrated and it's a mystery to us why the region isn't more well known as a tourist destination.",
            }
        ],
        'LatestArticleArr': [
            {
                id: 1,
                title: "Catch waves with an adventure guide",
                type: "Travel",
                date: "August 21 2017",
                imgpath: "../photo-1.jfif",
                description: "Gujarat is vastly underrated and it's a mystery to us why the region isn't more well known as a tourist destination.",
            },
            {
                id: 2,
                title: "Catch waves with an adventure guide",
                type: "Travel",
                date: "August 21 2017",
                imgpath: "../photo-1.jfif",
                description: "Gujarat is vastly underrated and it's a mystery to us why the region isn't more well known as a tourist destination.",
            },
            {
                id: 3,
                title: "Catch waves with an adventure guide",
                type: "Travel",
                date: "August 21 2017",
                imgpath: "../photo-1.jfif",
                description: "Gujarat is vastly underrated and it's a mystery to us why the region isn't more well known as a tourist destination.",
            },
            {
                id: 4,
                title: "Catch waves with an adventure guide",
                type: "Travel",
                date: "August 21 2017",
                imgpath: "../photo-1.jfif",
                description: "Gujarat is vastly underrated and it's a mystery to us why the region isn't more well known as a tourist destination.",
            },
            {
                id: 5,
                title: "Catch waves with an adventure guide",
                type: "Travel",
                date: "August 21 2017",
                imgpath: "../photo-1.jfif",
                description: "Gujarat is vastly underrated and it's a mystery to us why the region isn't more well known as a tourist destination.",
            },
            {
                id: 6,
                title: "Catch waves with an adventure guide",
                type: "Travel",
                date: "August 21 2017",
                imgpath: "../photo-1.jfif",
                description: "Gujarat is vastly underrated and it's a mystery to us why the region isn't more well known as a tourist destination.",
            },
            {
                id: 7,
                title: "Catch waves with an adventure guide",
                type: "Travel",
                date: "August 21 2017",
                imgpath: "../photo-1.jfif",
                description: "Gujarat is vastly underrated and it's a mystery to us why the region isn't more well known as a tourist destination.",
            }
        ]
    },
    fitness: {
        'title': 'Fitness',
        'TopPosts': [
            {
                id: 1,
                title: "Catch waves with an adventure guide",
                type: "Travel",
                date: "August 21 2017",
                imgpath: "../photo-1.jfif",
                description: "Gujarat is vastly underrated and it's a mystery to us why the region isn't more well known as a tourist destination.",
            },
            {
                id: 2,
                title: "Catch waves with an adventure guide",
                type: "Travel",
                date: "August 21 2017",
                imgpath: "../photo-1.jfif",
                description: "Gujarat is vastly underrated and it's a mystery to us why the region isn't more well known as a tourist destination.",
            },
            {
                id: 3,
                title: "Catch waves with an adventure guide",
                type: "Travel",
                date: "August 21 2017",
                imgpath: "../photo-1.jfif",
                description: "Gujarat is vastly underrated and it's a mystery to us why the region isn't more well known as a tourist destination.",
            },
            {
                id: 4,
                title: "Catch waves with an adventure guide",
                type: "Travel",
                date: "August 21 2017",
                imgpath: "../photo-1.jfif",
                description: "Gujarat is vastly underrated and it's a mystery to us why the region isn't more well known as a tourist destination.",
            }
        ],
        'LatestArticleArr': [
            {
                id: 1,
                title: "Catch waves with an adventure guide",
                type: "Travel",
                date: "August 21 2017",
                imgpath: "../photo-1.jfif",
                description: "Gujarat is vastly underrated and it's a mystery to us why the region isn't more well known as a tourist destination.",
            },
            {
                id: 2,
                title: "Catch waves with an adventure guide",
                type: "Travel",
                date: "August 21 2017",
                imgpath: "../photo-1.jfif",
                description: "Gujarat is vastly underrated and it's a mystery to us why the region isn't more well known as a tourist destination.",
            },
            {
                id: 3,
                title: "Catch waves with an adventure guide",
                type: "Travel",
                date: "August 21 2017",
                imgpath: "../photo-1.jfif",
                description: "Gujarat is vastly underrated and it's a mystery to us why the region isn't more well known as a tourist destination.",
            },
            {
                id: 4,
                title: "Catch waves with an adventure guide",
                type: "Travel",
                date: "August 21 2017",
                imgpath: "../photo-1.jfif",
                description: "Gujarat is vastly underrated and it's a mystery to us why the region isn't more well known as a tourist destination.",
            },
            {
                id: 5,
                title: "Catch waves with an adventure guide",
                type: "Travel",
                date: "August 21 2017",
                imgpath: "../photo-1.jfif",
                description: "Gujarat is vastly underrated and it's a mystery to us why the region isn't more well known as a tourist destination.",
            },
            {
                id: 6,
                title: "Catch waves with an adventure guide",
                type: "Travel",
                date: "August 21 2017",
                imgpath: "../photo-1.jfif",
                description: "Gujarat is vastly underrated and it's a mystery to us why the region isn't more well known as a tourist destination.",
            },
            {
                id: 7,
                title: "Catch waves with an adventure guide",
                type: "Travel",
                date: "August 21 2017",
                imgpath: "../photo-1.jfif",
                description: "Gujarat is vastly underrated and it's a mystery to us why the region isn't more well known as a tourist destination.",
            }
        ]
    },
    food: {
        'title': 'Food',
        'TopPosts': [
            {
                id: 1,
                title: "Catch waves with an adventure guide",
                type: "Travel",
                date: "August 21 2017",
                imgpath: "../photo-1.jfif",
                description: "Gujarat is vastly underrated and it's a mystery to us why the region isn't more well known as a tourist destination.",
            },
            {
                id: 2,
                title: "Catch waves with an adventure guide",
                type: "Travel",
                date: "August 21 2017",
                imgpath: "../photo-1.jfif",
                description: "Gujarat is vastly underrated and it's a mystery to us why the region isn't more well known as a tourist destination.",
            },
            {
                id: 3,
                title: "Catch waves with an adventure guide",
                type: "Travel",
                date: "August 21 2017",
                imgpath: "../photo-1.jfif",
                description: "Gujarat is vastly underrated and it's a mystery to us why the region isn't more well known as a tourist destination.",
            },
            {
                id: 4,
                title: "Catch waves with an adventure guide",
                type: "Travel",
                date: "August 21 2017",
                imgpath: "../photo-1.jfif",
                description: "Gujarat is vastly underrated and it's a mystery to us why the region isn't more well known as a tourist destination.",
            }
        ],
        'LatestArticleArr': [
            {
                id: 1,
                title: "Catch waves with an adventure guide",
                type: "Travel",
                date: "August 21 2017",
                imgpath: "../photo-1.jfif",
                description: "Gujarat is vastly underrated and it's a mystery to us why the region isn't more well known as a tourist destination.",
            },
            {
                id: 2,
                title: "Catch waves with an adventure guide",
                type: "Travel",
                date: "August 21 2017",
                imgpath: "../photo-1.jfif",
                description: "Gujarat is vastly underrated and it's a mystery to us why the region isn't more well known as a tourist destination.",
            },
            {
                id: 3,
                title: "Catch waves with an adventure guide",
                type: "Travel",
                date: "August 21 2017",
                imgpath: "../photo-1.jfif",
                description: "Gujarat is vastly underrated and it's a mystery to us why the region isn't more well known as a tourist destination.",
            },
            {
                id: 4,
                title: "Catch waves with an adventure guide",
                type: "Travel",
                date: "August 21 2017",
                imgpath: "../photo-1.jfif",
                description: "Gujarat is vastly underrated and it's a mystery to us why the region isn't more well known as a tourist destination.",
            },
            {
                id: 5,
                title: "Catch waves with an adventure guide",
                type: "Travel",
                date: "August 21 2017",
                imgpath: "../photo-1.jfif",
                description: "Gujarat is vastly underrated and it's a mystery to us why the region isn't more well known as a tourist destination.",
            },
            {
                id: 6,
                title: "Catch waves with an adventure guide",
                type: "Travel",
                date: "August 21 2017",
                imgpath: "../photo-1.jfif",
                description: "Gujarat is vastly underrated and it's a mystery to us why the region isn't more well known as a tourist destination.",
            },
            {
                id: 7,
                title: "Catch waves with an adventure guide",
                type: "Travel",
                date: "August 21 2017",
                imgpath: "../photo-1.jfif",
                description: "Gujarat is vastly underrated and it's a mystery to us why the region isn't more well known as a tourist destination.",
            }
        ]
    }
}
